CREATE TABLE TypeND(
  typeND_id INTEGER PRIMARY KEY,
  nameTypeND VARCHAR (30)
);
CREATE TABLE ND(
  ND_id INTEGER PRIMARY KEY,
  typeND_id INT REFERENCES TypeND ON UPDATE CASCADE ON DELETE NO ACTION,
  nameND VARCHAR(50),
  startDate DATE
);
CREATE TABLE TypeProduct(
  typeProduct_id INTEGER PRIMARY KEY,
  ND_id INT REFERENCES ND ON UPDATE CASCADE ON DELETE NO ACTION,
  nameTypeProduct VARCHAR(30),
  sokrName VARCHAR(10)
);
CREATE TABLE Products(
  serialNumber VARCHAR (20) PRIMARY KEY,
  typeProduct_id INT REFERENCES TypeProduct ON UPDATE CASCADE ON DELETE NO ACTION,
  dateRelease DATE,
  nameProduct VARCHAR (40),
  about VARCHAR (140)
);
CREATE TABLE Status(
  status_id INTEGER PRIMARY KEY,
  nameStatus VARCHAR (20)
);
CREATE TABLE Positions(
  position_id INTEGER PRIMARY KEY,
  namePosition VARCHAR (20)
);
CREATE TABLE Staff(
  staff_id INTEGER PRIMARY KEY,
  position_id INT REFERENCES Positions ON UPDATE CASCADE ON DELETE NO ACTION,
  FIOSotr VARCHAR (30),
  initials VARCHAR (6)
);
CREATE TABLE tests(
  test_id INTEGER PRIMARY KEY,
  serialNumber VARCHAR (20) REFERENCES Products ON UPDATE CASCADE ON DELETE NO ACTION,
  staff_id INT REFERENCES Staff ON UPDATE CASCADE ON DELETE NO ACTION,
  status_id INT REFERENCES Status ON UPDATE CASCADE ON DELETE NO ACTION,
  dateTest DATE,
  numberAct VARCHAR (10),
  pointND VARCHAR (10)
);
CREATE TABLE Applicants(
  applicant_id INTEGER PRIMARY KEY,
  nameApplicant VARCHAR (30),
  adress VARCHAR (60),
  phone VARCHAR (14),
  sign INTEGER
);
CREATE TABLE Supply(
  supply_id INTEGER PRIMARY KEY,
  serialNumber VARCHAR (20) REFERENCES Products ON UPDATE CASCADE ON DELETE NO ACTION,
  staff_id INT REFERENCES Staff ON UPDATE CASCADE ON DELETE NO ACTION,
  applicant_id INT REFERENCES Applicants ON UPDATE CASCADE ON DELETE NO ACTION,
  dateSupply DATE,
  numberDoc VARCHAR (20)
);
CREATE TABLE ReturnProduct(
  return_id INTEGER PRIMARY KEY,
  serialNumber VARCHAR (20) REFERENCES Products ON UPDATE CASCADE ON DELETE NO ACTION,
  staff_id INT REFERENCES Staff ON UPDATE CASCADE ON DELETE NO ACTION,
  applicant_id INT REFERENCES Applicants ON UPDATE CASCADE ON DELETE NO ACTION,
  dateReturn DATE,
  numberDoc VARCHAR (20)
);
CREATE TABLE Movement(
  mvmn_id INTEGER PRIMARY KEY,
  serialNumber VARCHAR (20) REFERENCES Products ON UPDATE CASCADE ON DELETE NO ACTION,
  dateMvmn DATE,
  status_id INT REFERENCES Status ON UPDATE CASCADE ON DELETE NO ACTION
);